### ISSUE TITLE
Library does not release the lock if cluster is unhealthy

### ISSUE THREAD

**Issue by v-boiko** [sky-uk/cqlmigrate#47] opened 2016-12-21 11:59 UTC
What happens:

Node acquires the lock
Starts SchemaLoader to do the migration
Schema loader checks cluster health which says "unhealthy"
Library throws an error and lock hangs there forever
Logs:

```
[2016-12-21 11:37:18,003] INFO  [main] u.s.c.Lock - [] Attempting to acquire lock for 'app.schema_migration', using client id '047b5b3c-ee9e-4059-b083-3a6bcd7e9259'
[2016-12-21 11:37:18,079] INFO  [main] u.s.c.CqlMigratorImpl - [] Loading cql files from [/tmp/cqlmigrate5345071027669587170]
[2016-12-21 11:37:18,093] INFO  [main] u.s.c.KeyspaceBootstrapper - [] Keyspace found, not applying bootstrap.cql
Exception in thread "main" uk.sky.cqlmigrate.exception.ClusterUnhealthyException: Cluster not healthy, the following hosts are down: [***]
        at uk.sky.cqlmigrate.ClusterHealth.check(ClusterHealth.java:28)
        at uk.sky.cqlmigrate.SessionContext.checkClusterHealth(SessionContext.java:35)
        at uk.sky.cqlmigrate.CqlLoader.load(CqlLoader.java:18)
        at uk.sky.cqlmigrate.SchemaLoader$Loader.apply(SchemaLoader.java:45)
        at uk.sky.cqlmigrate.CqlPaths.lambda$applyInSortedOrder$7(CqlPaths.java:49)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at uk.sky.cqlmigrate.CqlPaths.applyInSortedOrder(CqlPaths.java:49)
        at uk.sky.cqlmigrate.SchemaLoader.load(SchemaLoader.java:28)
        at uk.sky.cqlmigrate.CqlMigratorImpl.migrate(CqlMigratorImpl.java:90)
        at uk.sky.cqlmigrate.initializer.CqlMigrateInitializer.migrate(CqlMigrateInitializer.java:80)
        at uk.sky.cqlmigrate.initializer.CqlMigrateBundle.cqlMigrate(CqlMigrateBundle.java:62)
        at uk.sky.cqlmigrate.initializer.CqlMigrateBundle.run(CqlMigrateBundle.java:39)
        at uk.sky.cqlmigrate.initializer.CqlMigrateBundle.run(CqlMigrateBundle.java:15)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:79)
        at com.bskyb.App.main(App.java:54)
Registered app server agent with Node ID[9579] Component ID[1980] Application ID [68]
```

**Comment by jsravn** [comment] 2016-12-21 12:08
@v-boiko isn't this a duplicate of #48?

**Comment by v-boiko** [comment] 2016-12-21 12:10
No, it relates to it, but it's a different issue

Basically, if any exception is thrown during migration, the lock will not be released

**Comment by jsravn** [comment] 2016-12-21 13:13
You're right, that's a pretty terrible bug. I'm surprised it's not doing the lock in a try-with-resources.

**Comment by jsravn** [comment] 2016-12-21 13:14
@v-boiko Feel free to submit a PR to fix this issue if you want to get it fixed soon.

**Closed** 2017-03-03 09:57 UTC
Labels: bug
